### ISSUE TITLE
Redux Devtools should be collapsible or optional

### ISSUE THREAD

**Issue by mcasper** [devlocker/frontend#7]
The devtools sidebar takes up a bunch of room, and covers some key buttons. Makes it very hard to click around the app in dev mode. Should be opt-in or collapsible.

@mikeastock

**Comment by mikeastock** [comment]
The dev tools have a built in keyboard shortcut to hide them. `CTRL-H`. I just found that this morning :smile:

**Comment by mcasper** [comment]
Awesome, thanks!
